name: Docker Image CI

on: workflow_dispatch
  
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Check "NORUN" commit message
      id: check-commit
      run: echo "::set-output name=skip_workflow::false"

    - name: Checkout2
      if: steps.check-commit.outputs.skip_workflow != 'true'
      uses: actions/checkout@v4
      with: 
        ref: ${{ github.ref }}
