name: Condition Test

on: workflow_dispatch
  
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Step A
      id: check-commit
      run: echo "::set-output name=skip_workflow::false"

    - name: Step B
      if: steps.check-commit.outputs.skip_workflow != 'false'
      run: echo Step B

    - name: Step D
      if: steps.check-commit.outputs.skip_workflow != 'true'
      run: echo Step D
