name: Condition Test

on: workflow_dispatch
  
jobs:
  check-commit:
    runs-on: ubuntu-latest
    steps:
    - name: Step A
      id: check-commit
      run: |
        ##echo "STEP_B_IF=true" >> $GITHUB_ENV
        echo "STEP_D_IF=true" >> $GITHUB_ENV

    - name: Step B
      if: env.STEP_B_IF != null
      run: echo Step B

    - name: Step D
      if: env.STEP_D_IF != null
      run: echo Step D
